version: "3"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    env_file:
      - ./site/.env
    command: gunicorn --bind 0.0.0.0:8080 core.wsgi
    volumes:
      - ./site:/code
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - db
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./etc/nginx/:/etc/nginx/conf.d
      - ./site/staticfiles:/code/static
      - ./etc/certbot/conf:/etc/letsencrypt
      - ./etc/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    volumes:
      - ./etc/certbot/conf:/etc/letsencrypt
      - ./etc/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  postgres_data:
