version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    env_file:
      - ./.env
    command: gunicorn --bind 0.0.0.0:8080 djangox_project.wsgi
    volumes:
      - ./apps:/code
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - db
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./etc/nginx/:/etc/nginx/conf.d
      - ./apps/staticfiles:/code/static
    ports:
      - "80:80"
volumes:
  postgres_data:
