version: "3"

services:
  db:
    image: postgres:11.1-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    restart: always
    env_file:
      - ./site/.env
    volumes:
      - ./site:/code
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  postgres_data:
