version: "3"

services:
  db:
    image: postgres:11.1-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: web
    build: .
    restart: always
    env_file:
      - ./site/.env
    command: gunicorn --bind 0.0.0.0:8080 core.wsgi
    volumes:
      - ./site:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  nginx:
    image: "nginx"
    container_name: nginx
    restart: always
    volumes:
      - ./etc/nginx/:/etc/nginx/conf.d
      - ./site/staticfiles:/code/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
volumes:
  postgres_data:
